In [1]:
# Import Dependencies
import pandas as pd
from pathlib import Path

In [2]:
# Create reference to CSV files
startup_csv = Path("Resources/startup_data_cleaned.csv")
zipcode_csv = Path("Resources/zip_code_demographics.csv")

# Import CSVs into Pandas DataFrame
startup_df = pd.read_csv(startup_csv)
zipcode_df = pd.read_csv(zipcode_csv)

In [3]:
startup_df.head()

,Unnamed: 0,state_code,latitude,longitude,zip_code,id,city,Unnamed: 6,name,labels,...,object_id,has_VC,has_angel,has_roundA,has_roundB,has_roundC,has_roundD,avg_participants,is_top500,status
0,1005,CA,42.358880,-71.056820,92101,c:6669,San Diego,NaN,Bandsintown,1,...,c:6669,0,1,0,0,0,0,1.0000,0,acquired
1,204,CA,37.238916,-121.973718,95032,c:16283,Los Gatos,NaN,TriCipher,1,...,c:16283,1,0,0,1,1,1,4.7500,1,acquired
2,1001,CA,32.901049,-117.192656,92121,c:65620,San Diego,San Diego CA 92121,Plixi,1,...,c:65620,0,0,1,0,0,0,4.0000,1,acquired
3,738,CA,37.320309,-122.050040,95014,c:42668,Cupertino,Cupertino CA 95014,Solidcore Systems,1,...,c:42668,0,0,0,1,1,1,3.3333,1,acquired
4,1002,CA,37.779281,-122.419236,94105,c:65806,San Francisco,San Francisco CA 94105,Inhale Digital,0,...,c:65806,1,1,0,0,0,0,1.0000,1,closed

In [4]:
startup_df_dropcolumns = startup_df.drop(columns=['Unnamed: 0', 'id', 'Unnamed: 6', 'object_id', 'is_CA', 'is_NY', 'is_MA', 'is_TX', 'is_otherstate', 'is_software', 'is_web', 'is_mobile', 'is_enterprise', 'is_advertising', 'is_gamesvideo', 'is_ecommerce', 'is_biotech', 'is_consulting', 'is_othercategory'])
startup_df_dropcolumns.head()

,state_code,latitude,longitude,zip_code,city,name,labels,founded_at,closed_at,first_funding_at,...,category_code,has_VC,has_angel,has_roundA,has_roundB,has_roundC,has_roundD,avg_participants,is_top500,status
0,CA,42.358880,-71.056820,92101,San Diego,Bandsintown,1,1/1/2007,NaN,4/1/2009,...,music,0,1,0,0,0,0,1.0000,0,acquired
1,CA,37.238916,-121.973718,95032,Los Gatos,TriCipher,1,1/1/2000,NaN,2/14/2005,...,enterprise,1,0,0,1,1,1,4.7500,1,acquired
2,CA,32.901049,-117.192656,92121,San Diego,Plixi,1,3/18/2009,NaN,3/30/2010,...,web,0,0,1,0,0,0,4.0000,1,acquired
3,CA,37.320309,-122.050040,95014,Cupertino,Solidcore Systems,1,1/1/2002,NaN,2/17/2005,...,software,0,0,0,1,1,1,3.3333,1,acquired
4,CA,37.779281,-122.419236,94105,San Francisco,Inhale Digital,0,8/1/2010,10/1/2012,8/1/2010,...,games_video,1,1,0,0,0,0,1.0000,1,closed

In [5]:
zipcode_df.head()

,zip,lat,lng,city,state_id,state_name,population,density,county_name,po_box,dist_highway,dist2_large_airport,dist2_medium_airport,dist_to_shore,number_of_business,adjusted_gross_income,total_income_amount,number_of_returns
0,1001,42.06262,-72.62521,Agawam,MA,Massachusetts,16088,550.1,Hampden,0,1.387035,106.145765,12.946212,93.049251,438.0,598807,6.047690e+05,9320
1,1002,42.37633,-72.46462,Amherst,MA,Massachusetts,27323,198.1,Hampshire,0,14.438177,112.264368,21.080079,133.370144,571.0,989558,1.005796e+06,9880
2,1005,42.42117,-72.10655,Barre,MA,Massachusetts,4947,44.2,Worcester,0,16.788339,90.664964,25.547718,97.639881,97.0,164207,1.660540e+05,2490
3,1007,42.28163,-72.40009,Belchertown,MA,Massachusetts,15304,107.7,Hampshire,0,13.663839,101.552921,14.762395,114.406034,217.0,647074,6.547390e+05,7970
4,1008,42.18234,-72.95819,Blandford,MA,Massachusetts,1171,7.4,Hampden,0,2.593655,136.548797,20.177950,107.466779,18.0,47826,4.824100e+04,660

In [6]:
# Check zip values
zipcode_df.dtypes

zip                        int64
lat                      float64
lng                      float64
city                      object
state_id                  object
state_name                object
population                 int64
density                  float64
county_name               object
po_box                     int64
dist_highway             float64
dist2_large_airport      float64
dist2_medium_airport     float64
dist_to_shore            float64
number_of_business       float64
adjusted_gross_income      int64
total_income_amount      float64
number_of_returns          int64
dtype: object

In [7]:
# Change zip code column values to string
zipcode_df['zip'] = zipcode_df['zip'].astype(str)
zipcode_df.dtypes

zip                       object
lat                      float64
lng                      float64
city                      object
state_id                  object
state_name                object
population                 int64
density                  float64
county_name               object
po_box                     int64
dist_highway             float64
dist2_large_airport      float64
dist2_medium_airport     float64
dist_to_shore            float64
number_of_business       float64
adjusted_gross_income      int64
total_income_amount      float64
number_of_returns          int64
dtype: object

In [8]:
# Add '0' in front of zip codes that only have 4 characters
zipcode_df['zip'] = zipcode_df['zip'].apply(lambda x: '0' + x if len(x) == 4 else x)
zipcode_df

,zip,lat,lng,city,state_id,state_name,population,density,county_name,po_box,dist_highway,dist2_large_airport,dist2_medium_airport,dist_to_shore,number_of_business,adjusted_gross_income,total_income_amount,number_of_returns
0,01001,42.06262,-72.62521,Agawam,MA,Massachusetts,16088,550.1,Hampden,0,1.387035,106.145765,12.946212,93.049251,438.0,598807,6.047690e+05,9320
1,01002,42.37633,-72.46462,Amherst,MA,Massachusetts,27323,198.1,Hampshire,0,14.438177,112.264368,21.080079,133.370144,571.0,989558,1.005796e+06,9880
2,01005,42.42117,-72.10655,Barre,MA,Massachusetts,4947,44.2,Worcester,0,16.788339,90.664964,25.547718,97.639881,97.0,164207,1.660540e+05,2490
3,01007,42.28163,-72.40009,Belchertown,MA,Massachusetts,15304,107.7,Hampshire,0,13.663839,101.552921,14.762395,114.406034,217.0,647074,6.547390e+05,7970
4,01008,42.18234,-72.95819,Blandford,MA,Massachusetts,1171,7.4,Hampden,0,2.593655,136.548797,20.177950,107.466779,18.0,47826,4.824100e+04,660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33699,28388,35.18000,-79.40000,Southern Pines,NC,North Carolina,15158,198.2,Moore,1,29.611385,95.336980,35.052347,172.197809,637.0,652358,6.615840e+05,7740
33700,28765,35.96000,-82.12000,Spruce Pine,NC,North Carolina,10318,55.5,Mitchell,1,34.660884,134.931257,62.822117,402.428512,280.0,196579,1.988100e+05,3910
33701,40027,38.28000,-85.62000,Louisville,KY,Kentucky,21622,883.0,Jefferson,1,1.148362,15.509671,6.927500,400.646608,1133.0,1333163,1.350029e+06,11760
33702,40292,38.22000,-85.74000,Louisville,KY,Kentucky,12029,1936.4,Jefferson,1,1.017999,5.082523,6.724578,403.729631,270.0,323448,3.268630e+05,6500
33703,44316,41.08000,-81.52000,Akron,OH,Ohio,1723,1440.6,Summit,1,1.381451,46.050739,6.492610,50.216506,393.0,27191,2.777000e+04,380

In [9]:
# Change column name to match with the other dataframe
zipcode_df_newzip = zipcode_df.rename(columns={'zip': 'zip_code'})
zipcode_df_newzip

,zip_code,lat,lng,city,state_id,state_name,population,density,county_name,po_box,dist_highway,dist2_large_airport,dist2_medium_airport,dist_to_shore,number_of_business,adjusted_gross_income,total_income_amount,number_of_returns
0,01001,42.06262,-72.62521,Agawam,MA,Massachusetts,16088,550.1,Hampden,0,1.387035,106.145765,12.946212,93.049251,438.0,598807,6.047690e+05,9320
1,01002,42.37633,-72.46462,Amherst,MA,Massachusetts,27323,198.1,Hampshire,0,14.438177,112.264368,21.080079,133.370144,571.0,989558,1.005796e+06,9880
2,01005,42.42117,-72.10655,Barre,MA,Massachusetts,4947,44.2,Worcester,0,16.788339,90.664964,25.547718,97.639881,97.0,164207,1.660540e+05,2490
3,01007,42.28163,-72.40009,Belchertown,MA,Massachusetts,15304,107.7,Hampshire,0,13.663839,101.552921,14.762395,114.406034,217.0,647074,6.547390e+05,7970
4,01008,42.18234,-72.95819,Blandford,MA,Massachusetts,1171,7.4,Hampden,0,2.593655,136.548797,20.177950,107.466779,18.0,47826,4.824100e+04,660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33699,28388,35.18000,-79.40000,Southern Pines,NC,North Carolina,15158,198.2,Moore,1,29.611385,95.336980,35.052347,172.197809,637.0,652358,6.615840e+05,7740
33700,28765,35.96000,-82.12000,Spruce Pine,NC,North Carolina,10318,55.5,Mitchell,1,34.660884,134.931257,62.822117,402.428512,280.0,196579,1.988100e+05,3910
33701,40027,38.28000,-85.62000,Louisville,KY,Kentucky,21622,883.0,Jefferson,1,1.148362,15.509671,6.927500,400.646608,1133.0,1333163,1.350029e+06,11760
33702,40292,38.22000,-85.74000,Louisville,KY,Kentucky,12029,1936.4,Jefferson,1,1.017999,5.082523,6.724578,403.729631,270.0,323448,3.268630e+05,6500
33703,44316,41.08000,-81.52000,Akron,OH,Ohio,1723,1440.6,Summit,1,1.381451,46.050739,6.492610,50.216506,393.0,27191,2.777000e+04,380

In [10]:
# Drop unneeded columns
zipcode_df_clean = zipcode_df_newzip.drop(columns=['po_box', 'state_id', 'city', 'state_name'])
zipcode_df_clean

,zip_code,lat,lng,population,density,county_name,dist_highway,dist2_large_airport,dist2_medium_airport,dist_to_shore,number_of_business,adjusted_gross_income,total_income_amount,number_of_returns
0,01001,42.06262,-72.62521,16088,550.1,Hampden,1.387035,106.145765,12.946212,93.049251,438.0,598807,6.047690e+05,9320
1,01002,42.37633,-72.46462,27323,198.1,Hampshire,14.438177,112.264368,21.080079,133.370144,571.0,989558,1.005796e+06,9880
2,01005,42.42117,-72.10655,4947,44.2,Worcester,16.788339,90.664964,25.547718,97.639881,97.0,164207,1.660540e+05,2490
3,01007,42.28163,-72.40009,15304,107.7,Hampshire,13.663839,101.552921,14.762395,114.406034,217.0,647074,6.547390e+05,7970
4,01008,42.18234,-72.95819,1171,7.4,Hampden,2.593655,136.548797,20.177950,107.466779,18.0,47826,4.824100e+04,660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33699,28388,35.18000,-79.40000,15158,198.2,Moore,29.611385,95.336980,35.052347,172.197809,637.0,652358,6.615840e+05,7740
33700,28765,35.96000,-82.12000,10318,55.5,Mitchell,34.660884,134.931257,62.822117,402.428512,280.0,196579,1.988100e+05,3910
33701,40027,38.28000,-85.62000,21622,883.0,Jefferson,1.148362,15.509671,6.927500,400.646608,1133.0,1333163,1.350029e+06,11760
33702,40292,38.22000,-85.74000,12029,1936.4,Jefferson,1.017999,5.082523,6.724578,403.729631,270.0,323448,3.268630e+05,6500
33703,44316,41.08000,-81.52000,1723,1440.6,Summit,1.381451,46.050739,6.492610,50.216506,393.0,27191,2.777000e+04,380

In [11]:
# Join the two tables
merged_df = pd.merge(startup_df_dropcolumns, zipcode_df_clean, on='zip_code', how='inner')
merged_df

,state_code,latitude,longitude,zip_code,city,name,labels,founded_at,closed_at,first_funding_at,...,density,county_name,dist_highway,dist2_large_airport,dist2_medium_airport,dist_to_shore,number_of_business,adjusted_gross_income,total_income_amount,number_of_returns
0,CA,42.358880,-71.056820,92101,San Diego,Bandsintown,1,1/1/2007,NaN,4/1/2009,...,3090.7,San Diego,2.158829,1.972734,3.315078,3.499594,3846.0,2614117,2650133.0,25200
1,CA,37.238916,-121.973718,95032,Los Gatos,TriCipher,1,1/1/2000,NaN,2/14/2005,...,561.6,Santa Clara,4.877279,17.115840,25.601375,26.882493,965.0,5738753,5783111.0,13140
2,CA,32.901049,-117.192656,92121,San Diego,Plixi,1,3/18/2009,NaN,3/30/2010,...,129.7,San Diego,0.831302,18.238841,6.403279,4.965306,2932.0,494212,499351.0,2550
3,CA,37.320309,-122.050040,95014,Cupertino,Solidcore Systems,1,1/1/2002,NaN,2/17/2005,...,965.8,Santa Clara,2.952857,14.616111,12.295377,30.184050,1653.0,8095008,8145254.0,27030
4,CA,37.779281,-122.419236,94105,San Francisco,Inhale Digital,0,8/1/2010,10/1/2012,8/1/2010,...,10568.6,San Francisco,0.918062,17.380428,51.873742,7.727539,2216.0,3105528,3124831.0,8230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790,WA,47.802184,-122.196307,98021,Bothell,Dexterra,1,1/1/2000,NaN,8/17/2005,...,1307.6,Snohomish,0.044390,38.952904,13.785448,11.966311,681.0,2308559,2325163.0,15570
791,CA,37.740594,-122.376471,94107,San Francisco,CoTweet,1,1/1/2009,NaN,7/9/2009,...,5951.9,San Francisco,0.149818,16.050383,49.321312,8.898267,2343.0,4168994,4205247.0,17710
792,CA,37.408261,-122.015920,94089,Sunnyvale,Paracor Medical,0,1/1/1999,6/17/2012,6/29/2007,...,1490.6,Santa Clara,0.687591,9.324579,3.090437,36.504898,600.0,1582932,1590359.0,12130
793,CA,37.556732,-122.288378,94404,San Francisco,Causata,1,1/1/2009,NaN,10/5/2009,...,3246.0,San Mateo,0.916312,11.658279,24.892623,19.131821,948.0,4023341,4055424.0,17690
794,CA,37.386778,-121.966277,95054,Santa Clara,Asempra Technologies,1,1/1/2003,NaN,2/13/2006,...,1466.9,Santa Clara,1.174872,4.638658,7.863331,40.777124,1840.0,2470347,2479560.0,12410

In [12]:
from flask import Flask, jsonify
from flask_pymongo import PyMongo

In [13]:
app = Flask(__name__)

In [14]:
app.config["MONGO_URI"] = "mongodb://localhost:27017/merged_df"
mongo = PyMongo(app)

In [15]:
merged_data = merged_df.to_dict(orient='records')
mongo.db.startupsuccess.insert_many(merged_data)

InsertManyResult([ObjectId('674529556223ae89ac9dcb98'), ObjectId('674529556223ae89ac9dcb99'), ObjectId('674529556223ae89ac9dcb9a'), ObjectId('674529556223ae89ac9dcb9b'), ObjectId('674529556223ae89ac9dcb9c'), ObjectId('674529556223ae89ac9dcb9d'), ObjectId('674529556223ae89ac9dcb9e'), ObjectId('674529556223ae89ac9dcb9f'), ObjectId('674529556223ae89ac9dcba0'), ObjectId('674529556223ae89ac9dcba1'), ObjectId('674529556223ae89ac9dcba2'), ObjectId('674529556223ae89ac9dcba3'), ObjectId('674529556223ae89ac9dcba4'), ObjectId('674529556223ae89ac9dcba5'), ObjectId('674529556223ae89ac9dcba6'), ObjectId('674529556223ae89ac9dcba7'), ObjectId('674529556223ae89ac9dcba8'), ObjectId('674529556223ae89ac9dcba9'), ObjectId('674529556223ae89ac9dcbaa'), ObjectId('674529556223ae89ac9dcbab'), ObjectId('674529556223ae89ac9dcbac'), ObjectId('674529556223ae89ac9dcbad'), ObjectId('674529556223ae89ac9dcbae'), ObjectId('674529556223ae89ac9dcbaf'), ObjectId('674529556223ae89ac9dcbb0'), ObjectId('674529556223ae89ac9dcbb1'), ObjectId('674529556223ae89ac9dcbb2'), ObjectId('674529556223ae89ac9dcbb3'), ObjectId('674529556223ae89ac9dcbb4'), ObjectId('674529556223ae89ac9dcbb5'), ObjectId('674529556223ae89ac9dcbb6'), ObjectId('674529556223ae89ac9dcbb7'), ObjectId('674529556223ae89ac9dcbb8'), ObjectId('674529556223ae89ac9dcbb9'), ObjectId('674529556223ae89ac9dcbba'), ObjectId('674529556223ae89ac9dcbbb'), ObjectId('674529556223ae89ac9dcbbc'), ObjectId('674529556223ae89ac9dcbbd'), ObjectId('674529556223ae89ac9dcbbe'), ObjectId('674529556223ae89ac9dcbbf'), ObjectId('674529556223ae89ac9dcbc0'), ObjectId('674529556223ae89ac9dcbc1'), ObjectId('674529556223ae89ac9dcbc2'), ObjectId('674529556223ae89ac9dcbc3'), ObjectId('674529556223ae89ac9dcbc4'), ObjectId('674529556223ae89ac9dcbc5'), ObjectId('674529556223ae89ac9dcbc6'), ObjectId('674529556223ae89ac9dcbc7'), ObjectId('674529556223ae89ac9dcbc8'), ObjectId('674529556223ae89ac9dcbc9'), ObjectId('674529556223ae89ac9dcbca'), ObjectId('674529556223ae89ac9dcbcb'), ObjectId('674529556223ae89ac9dcbcc'), ObjectId('674529556223ae89ac9dcbcd'), ObjectId('674529556223ae89ac9dcbce'), ObjectId('674529556223ae89ac9dcbcf'), ObjectId('674529556223ae89ac9dcbd0'), ObjectId('674529556223ae89ac9dcbd1'), ObjectId('674529556223ae89ac9dcbd2'), ObjectId('674529556223ae89ac9dcbd3'), ObjectId('674529556223ae89ac9dcbd4'), ObjectId('674529556223ae89ac9dcbd5'), ObjectId('674529556223ae89ac9dcbd6'), ObjectId('674529556223ae89ac9dcbd7'), ObjectId('674529556223ae89ac9dcbd8'), ObjectId('674529556223ae89ac9dcbd9'), ObjectId('674529556223ae89ac9dcbda'), ObjectId('674529556223ae89ac9dcbdb'), ObjectId('674529556223ae89ac9dcbdc'), ObjectId('674529556223ae89ac9dcbdd'), ObjectId('674529556223ae89ac9dcbde'), ObjectId('674529556223ae89ac9dcbdf'), ObjectId('674529556223ae89ac9dcbe0'), ObjectId('674529556223ae89ac9dcbe1'), ObjectId('674529556223ae89ac9dcbe2'), ObjectId('674529556223ae89ac9dcbe3'), ObjectId('674529556223ae89ac9dcbe4'), ObjectId('674529556223ae89ac9dcbe5'), ObjectId('674529556223ae89ac9dcbe6'), ObjectId('674529556223ae89ac9dcbe7'), ObjectId('674529556223ae89ac9dcbe8'), ObjectId('674529556223ae89ac9dcbe9'), ObjectId('674529556223ae89ac9dcbea'), ObjectId('674529556223ae89ac9dcbeb'), ObjectId('674529556223ae89ac9dcbec'), ObjectId('674529556223ae89ac9dcbed'), ObjectId('674529556223ae89ac9dcbee'), ObjectId('674529556223ae89ac9dcbef'), ObjectId('674529556223ae89ac9dcbf0'), ObjectId('674529556223ae89ac9dcbf1'), ObjectId('674529556223ae89ac9dcbf2'), ObjectId('674529556223ae89ac9dcbf3'), ObjectId('674529556223ae89ac9dcbf4'), ObjectId('674529556223ae89ac9dcbf5'), ObjectId('674529556223ae89ac9dcbf6'), ObjectId('674529556223ae89ac9dcbf7'), ObjectId('674529556223ae89ac9dcbf8'), ObjectId('674529556223ae89ac9dcbf9'), ObjectId('674529556223ae89ac9dcbfa'), ObjectId('674529556223ae89ac9dcbfb'), ObjectId('674529556223ae89ac9dcbfc'), ObjectId('674529556223ae89ac9dcbfd'), ObjectId('674529556223ae89ac9dcbfe'), ObjectId('674529556223ae89ac9dcbff'), ObjectId('674529556223ae89ac9dcc00'), ObjectId('674529556223ae89ac9dcc01'), ObjectId('674529556223ae89ac9dcc02'), ObjectId('674529556223ae89ac9dcc03'), ObjectId('674529556223ae89ac9dcc04'), ObjectId('674529556223ae89ac9dcc05'), ObjectId('674529556223ae89ac9dcc06'), ObjectId('674529556223ae89ac9dcc07'), ObjectId('674529556223ae89ac9dcc08'), ObjectId('674529556223ae89ac9dcc09'), ObjectId('674529556223ae89ac9dcc0a'), ObjectId('674529556223ae89ac9dcc0b'), ObjectId('674529556223ae89ac9dcc0c'), ObjectId('674529556223ae89ac9dcc0d'), ObjectId('674529556223ae89ac9dcc0e'), ObjectId('674529556223ae89ac9dcc0f'), ObjectId('674529556223ae89ac9dcc10'), ObjectId('674529556223ae89ac9dcc11'), ObjectId('674529556223ae89ac9dcc12'), ObjectId('674529556223ae89ac9dcc13'), ObjectId('674529556223ae89ac9dcc14'), ObjectId('674529556223ae89ac9dcc15'), ObjectId('674529556223ae89ac9dcc16'), ObjectId('674529556223ae89ac9dcc17'), ObjectId('674529556223ae89ac9dcc18'), ObjectId('674529556223ae89ac9dcc19'), ObjectId('674529556223ae89ac9dcc1a'), ObjectId('674529556223ae89ac9dcc1b'), ObjectId('674529556223ae89ac9dcc1c'), ObjectId('674529556223ae89ac9dcc1d'), ObjectId('674529556223ae89ac9dcc1e'), ObjectId('674529556223ae89ac9dcc1f'), ObjectId('674529556223ae89ac9dcc20'), ObjectId('674529556223ae89ac9dcc21'), ObjectId('674529556223ae89ac9dcc22'), ObjectId('674529556223ae89ac9dcc23'), ObjectId('674529556223ae89ac9dcc24'), ObjectId('674529556223ae89ac9dcc25'), ObjectId('674529556223ae89ac9dcc26'), ObjectId('674529556223ae89ac9dcc27'), ObjectId('674529556223ae89ac9dcc28'), ObjectId('674529556223ae89ac9dcc29'), ObjectId('674529556223ae89ac9dcc2a'), ObjectId('674529556223ae89ac9dcc2b'), ObjectId('674529556223ae89ac9dcc2c'), ObjectId('674529556223ae89ac9dcc2d'), ObjectId('674529556223ae89ac9dcc2e'), ObjectId('674529556223ae89ac9dcc2f'), ObjectId('674529556223ae89ac9dcc30'), ObjectId('674529556223ae89ac9dcc31'), ObjectId('674529556223ae89ac9dcc32'), ObjectId('674529556223ae89ac9dcc33'), ObjectId('674529556223ae89ac9dcc34'), ObjectId('674529556223ae89ac9dcc35'), ObjectId('674529556223ae89ac9dcc36'), ObjectId('674529556223ae89ac9dcc37'), ObjectId('674529556223ae89ac9dcc38'), ObjectId('674529556223ae89ac9dcc39'), ObjectId('674529556223ae89ac9dcc3a'), ObjectId('674529556223ae89ac9dcc3b'), ObjectId('674529556223ae89ac9dcc3c'), ObjectId('674529556223ae89ac9dcc3d'), ObjectId('674529556223ae89ac9dcc3e'), ObjectId('674529556223ae89ac9dcc3f'), ObjectId('674529556223ae89ac9dcc40'), ObjectId('674529556223ae89ac9dcc41'), ObjectId('674529556223ae89ac9dcc42'), ObjectId('674529556223ae89ac9dcc43'), ObjectId('674529556223ae89ac9dcc44'), ObjectId('674529556223ae89ac9dcc45'), ObjectId('674529556223ae89ac9dcc46'), ObjectId('674529556223ae89ac9dcc47'), ObjectId('674529556223ae89ac9dcc48'), ObjectId('674529556223ae89ac9dcc49'), ObjectId('674529556223ae89ac9dcc4a'), ObjectId('674529556223ae89ac9dcc4b'), ObjectId('674529556223ae89ac9dcc4c'), ObjectId('674529556223ae89ac9dcc4d'), ObjectId('674529556223ae89ac9dcc4e'), ObjectId('674529556223ae89ac9dcc4f'), ObjectId('674529556223ae89ac9dcc50'), ObjectId('674529556223ae89ac9dcc51'), ObjectId('674529556223ae89ac9dcc52'), ObjectId('674529556223ae89ac9dcc53'), ObjectId('674529556223ae89ac9dcc54'), ObjectId('674529556223ae89ac9dcc55'), ObjectId('674529556223ae89ac9dcc56'), ObjectId('674529556223ae89ac9dcc57'), ObjectId('674529556223ae89ac9dcc58'), ObjectId('674529556223ae89ac9dcc59'), ObjectId('674529556223ae89ac9dcc5a'), ObjectId('674529556223ae89ac9dcc5b'), ObjectId('674529556223ae89ac9dcc5c'), ObjectId('674529556223ae89ac9dcc5d'), ObjectId('674529556223ae89ac9dcc5e'), ObjectId('674529556223ae89ac9dcc5f'), ObjectId('674529556223ae89ac9dcc60'), ObjectId('674529556223ae89ac9dcc61'), ObjectId('674529556223ae89ac9dcc62'), ObjectId('674529556223ae89ac9dcc63'), ObjectId('674529556223ae89ac9dcc64'), ObjectId('674529556223ae89ac9dcc65'), ObjectId('674529556223ae89ac9dcc66'), ObjectId('674529556223ae89ac9dcc67'), ObjectId('674529556223ae89ac9dcc68'), ObjectId('674529556223ae89ac9dcc69'), ObjectId('674529556223ae89ac9dcc6a'), ObjectId('674529556223ae89ac9dcc6b'), ObjectId('674529556223ae89ac9dcc6c'), ObjectId('674529556223ae89ac9dcc6d'), ObjectId('674529556223ae89ac9dcc6e'), ObjectId('674529556223ae89ac9dcc6f'), ObjectId('674529556223ae89ac9dcc70'), ObjectId('674529556223ae89ac9dcc71'), ObjectId('674529556223ae89ac9dcc72'), ObjectId('674529556223ae89ac9dcc73'), ObjectId('674529556223ae89ac9dcc74'), ObjectId('674529556223ae89ac9dcc75'), ObjectId('674529556223ae89ac9dcc76'), ObjectId('674529556223ae89ac9dcc77'), ObjectId('674529556223ae89ac9dcc78'), ObjectId('674529556223ae89ac9dcc79'), ObjectId('674529556223ae89ac9dcc7a'), ObjectId('674529556223ae89ac9dcc7b'), ObjectId('674529556223ae89ac9dcc7c'), ObjectId('674529556223ae89ac9dcc7d'), ObjectId('674529556223ae89ac9dcc7e'), ObjectId('674529556223ae89ac9dcc7f'), ObjectId('674529556223ae89ac9dcc80'), ObjectId('674529556223ae89ac9dcc81'), ObjectId('674529556223ae89ac9dcc82'), ObjectId('674529556223ae89ac9dcc83'), ObjectId('674529556223ae89ac9dcc84'), ObjectId('674529556223ae89ac9dcc85'), ObjectId('674529556223ae89ac9dcc86'), ObjectId('674529556223ae89ac9dcc87'), ObjectId('674529556223ae89ac9dcc88'), ObjectId('674529556223ae89ac9dcc89'), ObjectId('674529556223ae89ac9dcc8a'), ObjectId('674529556223ae89ac9dcc8b'), ObjectId('674529556223ae89ac9dcc8c'), ObjectId('674529556223ae89ac9dcc8d'), ObjectId('674529556223ae89ac9dcc8e'), ObjectId('674529556223ae89ac9dcc8f'), ObjectId('674529556223ae89ac9dcc90'), ObjectId('674529556223ae89ac9dcc91'), ObjectId('674529556223ae89ac9dcc92'), ObjectId('674529556223ae89ac9dcc93'), ObjectId('674529556223ae89ac9dcc94'), ObjectId('674529556223ae89ac9dcc95'), ObjectId('674529556223ae89ac9dcc96'), ObjectId('674529556223ae89ac9dcc97'), ObjectId('674529556223ae89ac9dcc98'), ObjectId('674529556223ae89ac9dcc99'), ObjectId('674529556223ae89ac9dcc9a'), ObjectId('674529556223ae89ac9dcc9b'), ObjectId('674529556223ae89ac9dcc9c'), ObjectId('674529556223ae89ac9dcc9d'), ObjectId('674529556223ae89ac9dcc9e'), ObjectId('674529556223ae89ac9dcc9f'), ObjectId('674529556223ae89ac9dcca0'), ObjectId('674529556223ae89ac9dcca1'), ObjectId('674529556223ae89ac9dcca2'), ObjectId('674529556223ae89ac9dcca3'), ObjectId('674529556223ae89ac9dcca4'), ObjectId('674529556223ae89ac9dcca5'), ObjectId('674529556223ae89ac9dcca6'), ObjectId('674529556223ae89ac9dcca7'), ObjectId('674529556223ae89ac9dcca8'), ObjectId('674529556223ae89ac9dcca9'), ObjectId('674529556223ae89ac9dccaa'), ObjectId('674529556223ae89ac9dccab'), ObjectId('674529556223ae89ac9dccac'), ObjectId('674529556223ae89ac9dccad'), ObjectId('674529556223ae89ac9dccae'), ObjectId('674529556223ae89ac9dccaf'), ObjectId('674529556223ae89ac9dccb0'), ObjectId('674529556223ae89ac9dccb1'), ObjectId('674529556223ae89ac9dccb2'), ObjectId('674529556223ae89ac9dccb3'), ObjectId('674529556223ae89ac9dccb4'), ObjectId('674529556223ae89ac9dccb5'), ObjectId('674529556223ae89ac9dccb6'), ObjectId('674529556223ae89ac9dccb7'), ObjectId('674529556223ae89ac9dccb8'), ObjectId('674529556223ae89ac9dccb9'), ObjectId('674529556223ae89ac9dccba'), ObjectId('674529556223ae89ac9dccbb'), ObjectId('674529556223ae89ac9dccbc'), ObjectId('674529556223ae89ac9dccbd'), ObjectId('674529556223ae89ac9dccbe'), ObjectId('674529556223ae89ac9dccbf'), ObjectId('674529556223ae89ac9dccc0'), ObjectId('674529556223ae89ac9dccc1'), ObjectId('674529556223ae89ac9dccc2'), ObjectId('674529556223ae89ac9dccc3'), ObjectId('674529556223ae89ac9dccc4'), ObjectId('674529556223ae89ac9dccc5'), ObjectId('674529556223ae89ac9dccc6'), ObjectId('674529556223ae89ac9dccc7'), ObjectId('674529556223ae89ac9dccc8'), ObjectId('674529556223ae89ac9dccc9'), ObjectId('674529556223ae89ac9dccca'), ObjectId('674529556223ae89ac9dcccb'), ObjectId('674529556223ae89ac9dcccc'), ObjectId('674529556223ae89ac9dcccd'), ObjectId('674529556223ae89ac9dccce'), ObjectId('674529556223ae89ac9dcccf'), ObjectId('674529556223ae89ac9dccd0'), ObjectId('674529556223ae89ac9dccd1'), ObjectId('674529556223ae89ac9dccd2'), ObjectId('674529556223ae89ac9dccd3'), ObjectId('674529556223ae89ac9dccd4'), ObjectId('674529556223ae89ac9dccd5'), ObjectId('674529556223ae89ac9dccd6'), ObjectId('674529556223ae89ac9dccd7'), ObjectId('674529556223ae89ac9dccd8'), ObjectId('674529556223ae89ac9dccd9'), ObjectId('674529556223ae89ac9dccda'), ObjectId('674529556223ae89ac9dccdb'), ObjectId('674529556223ae89ac9dccdc'), ObjectId('674529556223ae89ac9dccdd'), ObjectId('674529556223ae89ac9dccde'), ObjectId('674529556223ae89ac9dccdf'), ObjectId('674529556223ae89ac9dcce0'), ObjectId('674529556223ae89ac9dcce1'), ObjectId('674529556223ae89ac9dcce2'), ObjectId('674529556223ae89ac9dcce3'), ObjectId('674529556223ae89ac9dcce4'), ObjectId('674529556223ae89ac9dcce5'), ObjectId('674529556223ae89ac9dcce6'), ObjectId('674529556223ae89ac9dcce7'), ObjectId('674529556223ae89ac9dcce8'), ObjectId('674529556223ae89ac9dcce9'), ObjectId('674529556223ae89ac9dccea'), ObjectId('674529556223ae89ac9dcceb'), ObjectId('674529556223ae89ac9dccec'), ObjectId('674529556223ae89ac9dcced'), ObjectId('674529556223ae89ac9dccee'), ObjectId('674529556223ae89ac9dccef'), ObjectId('674529556223ae89ac9dccf0'), ObjectId('674529556223ae89ac9dccf1'), ObjectId('674529556223ae89ac9dccf2'), ObjectId('674529556223ae89ac9dccf3'), ObjectId('674529556223ae89ac9dccf4'), ObjectId('674529556223ae89ac9dccf5'), ObjectId('674529556223ae89ac9dccf6'), ObjectId('674529556223ae89ac9dccf7'), ObjectId('674529556223ae89ac9dccf8'), ObjectId('674529556223ae89ac9dccf9'), ObjectId('674529556223ae89ac9dccfa'), ObjectId('674529556223ae89ac9dccfb'), ObjectId('674529556223ae89ac9dccfc'), ObjectId('674529556223ae89ac9dccfd'), ObjectId('674529556223ae89ac9dccfe'), ObjectId('674529556223ae89ac9dccff'), ObjectId('674529556223ae89ac9dcd00'), ObjectId('674529556223ae89ac9dcd01'), ObjectId('674529556223ae89ac9dcd02'), ObjectId('674529556223ae89ac9dcd03'), ObjectId('674529556223ae89ac9dcd04'), ObjectId('674529556223ae89ac9dcd05'), ObjectId('674529556223ae89ac9dcd06'), ObjectId('674529556223ae89ac9dcd07'), ObjectId('674529556223ae89ac9dcd08'), ObjectId('674529556223ae89ac9dcd09'), ObjectId('674529556223ae89ac9dcd0a'), ObjectId('674529556223ae89ac9dcd0b'), ObjectId('674529556223ae89ac9dcd0c'), ObjectId('674529556223ae89ac9dcd0d'), ObjectId('674529556223ae89ac9dcd0e'), ObjectId('674529556223ae89ac9dcd0f'), ObjectId('674529556223ae89ac9dcd10'), ObjectId('674529556223ae89ac9dcd11'), ObjectId('674529556223ae89ac9dcd12'), ObjectId('674529556223ae89ac9dcd13'), ObjectId('674529556223ae89ac9dcd14'), ObjectId('674529556223ae89ac9dcd15'), ObjectId('674529556223ae89ac9dcd16'), ObjectId('674529556223ae89ac9dcd17'), ObjectId('674529556223ae89ac9dcd18'), ObjectId('674529556223ae89ac9dcd19'), ObjectId('674529556223ae89ac9dcd1a'), ObjectId('674529556223ae89ac9dcd1b'), ObjectId('674529556223ae89ac9dcd1c'), ObjectId('674529556223ae89ac9dcd1d'), ObjectId('674529556223ae89ac9dcd1e'), ObjectId('674529556223ae89ac9dcd1f'), ObjectId('674529556223ae89ac9dcd20'), ObjectId('674529556223ae89ac9dcd21'), ObjectId('674529556223ae89ac9dcd22'), ObjectId('674529556223ae89ac9dcd23'), ObjectId('674529556223ae89ac9dcd24'), ObjectId('674529556223ae89ac9dcd25'), ObjectId('674529556223ae89ac9dcd26'), ObjectId('674529556223ae89ac9dcd27'), ObjectId('674529556223ae89ac9dcd28'), ObjectId('674529556223ae89ac9dcd29'), ObjectId('674529556223ae89ac9dcd2a'), ObjectId('674529556223ae89ac9dcd2b'), ObjectId('674529556223ae89ac9dcd2c'), ObjectId('674529556223ae89ac9dcd2d'), ObjectId('674529556223ae89ac9dcd2e'), ObjectId('674529556223ae89ac9dcd2f'), ObjectId('674529556223ae89ac9dcd30'), ObjectId('674529556223ae89ac9dcd31'), ObjectId('674529556223ae89ac9dcd32'), ObjectId('674529556223ae89ac9dcd33'), ObjectId('674529556223ae89ac9dcd34'), ObjectId('674529556223ae89ac9dcd35'), ObjectId('674529556223ae89ac9dcd36'), ObjectId('674529556223ae89ac9dcd37'), ObjectId('674529556223ae89ac9dcd38'), ObjectId('674529556223ae89ac9dcd39'), ObjectId('674529556223ae89ac9dcd3a'), ObjectId('674529556223ae89ac9dcd3b'), ObjectId('674529556223ae89ac9dcd3c'), ObjectId('674529556223ae89ac9dcd3d'), ObjectId('674529556223ae89ac9dcd3e'), ObjectId('674529556223ae89ac9dcd3f'), ObjectId('674529556223ae89ac9dcd40'), ObjectId('674529556223ae89ac9dcd41'), ObjectId('674529556223ae89ac9dcd42'), ObjectId('674529556223ae89ac9dcd43'), ObjectId('674529556223ae89ac9dcd44'), ObjectId('674529556223ae89ac9dcd45'), ObjectId('674529556223ae89ac9dcd46'), ObjectId('674529556223ae89ac9dcd47'), ObjectId('674529556223ae89ac9dcd48'), ObjectId('674529556223ae89ac9dcd49'), ObjectId('674529556223ae89ac9dcd4a'), ObjectId('674529556223ae89ac9dcd4b'), ObjectId('674529556223ae89ac9dcd4c'), ObjectId('674529556223ae89ac9dcd4d'), ObjectId('674529556223ae89ac9dcd4e'), ObjectId('674529556223ae89ac9dcd4f'), ObjectId('674529556223ae89ac9dcd50'), ObjectId('674529556223ae89ac9dcd51'), ObjectId('674529556223ae89ac9dcd52'), ObjectId('674529556223ae89ac9dcd53'), ObjectId('674529556223ae89ac9dcd54'), ObjectId('674529556223ae89ac9dcd55'), ObjectId('674529556223ae89ac9dcd56'), ObjectId('674529556223ae89ac9dcd57'), ObjectId('674529556223ae89ac9dcd58'), ObjectId('674529556223ae89ac9dcd59'), ObjectId('674529556223ae89ac9dcd5a'), ObjectId('674529556223ae89ac9dcd5b'), ObjectId('674529556223ae89ac9dcd5c'), ObjectId('674529556223ae89ac9dcd5d'), ObjectId('674529556223ae89ac9dcd5e'), ObjectId('674529556223ae89ac9dcd5f'), ObjectId('674529556223ae89ac9dcd60'), ObjectId('674529556223ae89ac9dcd61'), ObjectId('674529556223ae89ac9dcd62'), ObjectId('674529556223ae89ac9dcd63'), ObjectId('674529556223ae89ac9dcd64'), ObjectId('674529556223ae89ac9dcd65'), ObjectId('674529556223ae89ac9dcd66'), ObjectId('674529556223ae89ac9dcd67'), ObjectId('674529556223ae89ac9dcd68'), ObjectId('674529556223ae89ac9dcd69'), ObjectId('674529556223ae89ac9dcd6a'), ObjectId('674529556223ae89ac9dcd6b'), ObjectId('674529556223ae89ac9dcd6c'), ObjectId('674529556223ae89ac9dcd6d'), ObjectId('674529556223ae89ac9dcd6e'), ObjectId('674529556223ae89ac9dcd6f'), ObjectId('674529556223ae89ac9dcd70'), ObjectId('674529556223ae89ac9dcd71'), ObjectId('674529556223ae89ac9dcd72'), ObjectId('674529556223ae89ac9dcd73'), ObjectId('674529556223ae89ac9dcd74'), ObjectId('674529556223ae89ac9dcd75'), ObjectId('674529556223ae89ac9dcd76'), ObjectId('674529556223ae89ac9dcd77'), ObjectId('674529556223ae89ac9dcd78'), ObjectId('674529556223ae89ac9dcd79'), ObjectId('674529556223ae89ac9dcd7a'), ObjectId('674529556223ae89ac9dcd7b'), ObjectId('674529556223ae89ac9dcd7c'), ObjectId('674529556223ae89ac9dcd7d'), ObjectId('674529556223ae89ac9dcd7e'), ObjectId('674529556223ae89ac9dcd7f'), ObjectId('674529556223ae89ac9dcd80'), ObjectId('674529556223ae89ac9dcd81'), ObjectId('674529556223ae89ac9dcd82'), ObjectId('674529556223ae89ac9dcd83'), ObjectId('674529556223ae89ac9dcd84'), ObjectId('674529556223ae89ac9dcd85'), ObjectId('674529556223ae89ac9dcd86'), ObjectId('674529556223ae89ac9dcd87'), ObjectId('674529556223ae89ac9dcd88'), ObjectId('674529556223ae89ac9dcd89'), ObjectId('674529556223ae89ac9dcd8a'), ObjectId('674529556223ae89ac9dcd8b'), ObjectId('674529556223ae89ac9dcd8c'), ObjectId('674529556223ae89ac9dcd8d'), ObjectId('674529556223ae89ac9dcd8e'), ObjectId('674529556223ae89ac9dcd8f'), ObjectId('674529556223ae89ac9dcd90'), ObjectId('674529556223ae89ac9dcd91'), ObjectId('674529556223ae89ac9dcd92'), ObjectId('674529556223ae89ac9dcd93'), ObjectId('674529556223ae89ac9dcd94'), ObjectId('674529556223ae89ac9dcd95'), ObjectId('674529556223ae89ac9dcd96'), ObjectId('674529556223ae89ac9dcd97'), ObjectId('674529556223ae89ac9dcd98'), ObjectId('674529556223ae89ac9dcd99'), ObjectId('674529556223ae89ac9dcd9a'), ObjectId('674529556223ae89ac9dcd9b'), ObjectId('674529556223ae89ac9dcd9c'), ObjectId('674529556223ae89ac9dcd9d'), ObjectId('674529556223ae89ac9dcd9e'), ObjectId('674529556223ae89ac9dcd9f'), ObjectId('674529556223ae89ac9dcda0'), ObjectId('674529556223ae89ac9dcda1'), ObjectId('674529556223ae89ac9dcda2'), ObjectId('674529556223ae89ac9dcda3'), ObjectId('674529556223ae89ac9dcda4'), ObjectId('674529556223ae89ac9dcd

In [16]:
@app.route('/data')
def get_data():
    data = mongo.db.startupsuccess.find()
    return jsonify([record for record in data])

In [ ]:
@app.route('index.html')
def index():
    return render_template("index.html")

In [17]:
if __name__ == '__main__':
    app.run(debug=True)

 * Serving Flask app '__main__'
 * Debug mode: on

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Applications/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Applications/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/Applications/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 654, in initialize
    self.init_sockets()
  File "/Applications/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 331, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 253, in _bind_socket
    return self._try_bind_socket(s, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 229, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/Applications/anaconda3/lib/python3.12/site-packages/zmq/sugar/socket.py", line 302, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 564, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use (addr='tcp://127.0.0.1:56323')

SystemExit: 1

/Applications/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)